### ISSUE TITLE
Doesn't seem to be published on NPM

### ISSUE THREAD

**Issue by phocks** [nanostores/logger#11]
https://registry.npmjs.org/@nanostores/logger <- not found

**Comment by euaaaio** [comment]
This package was under development, but worked when installed directly from the repository.
But now I am updating and refactoring it to support the new version of Nanostores and other new features.

I plan to publish it next week.

**Comment by euaaaio** [comment]
v0.1.0 released.
The complete documentation will be written up tomorrow.
