### ISSUE TITLE
Export 'actionId' (imported as 'actionId') was not found in 'nanostores'

### ISSUE THREAD

**Issue by IzoldaV** [nanostores/logger#16]
![image](https://github.com/nanostores/logger/assets/25500185/86134cd5-6d52-489f-8e04-5c26f62cad1b)
Hello. When installing the logger, I encountered the fact that the package was trying to get a non-exported variable.

"@nanostores/react": "^0.7.1",
"@nanostores/logger": "^0.2.3",

**Comment by ai** [comment]
What version of `nanostores` do you use?

**Comment by IzoldaV** [comment]
Andrey, thanks for the tip.
I just switched from version 0.8.1 to the latest version, and everything worked. I did not update the full set of dependencies when installing the logger.
